# ─── Configuration ────────────────────────────────────────────────────────────
# All targets run from the project root. ENV picks which compose override and
# which env files to load (dev / test / prod).
ENV ?= dev
export ENV

COMPOSE_BASE = docker/docker-compose.yml
COMPOSE_ENV  = docker/docker-compose.$(ENV).yml
ENV_CONFIG   = env/.env.$(ENV).config
ENV_SECRETS  = env/.env.$(ENV)

COMPOSE = docker compose \
    --env-file $(ENV_CONFIG) \
    --env-file $(ENV_SECRETS) \
    -f $(COMPOSE_BASE) \
    -f $(COMPOSE_ENV)

# Project name from config (used for `docker exec` targets)
PROJECT_NAME := $(shell grep -E '^PROJECT_NAME=' $(ENV_CONFIG) 2>/dev/null | cut -d= -f2)
ifeq ($(PROJECT_NAME),)
PROJECT_NAME := myapp
endif

.PHONY: help dev prod stop restart logs ps shell db-shell \
        migrate migration stamp-baseline \
        test test-unit test-from-dev \
        deploy-test deploy-prod \
        setup-server lint format \
        lock sync

# ─── Help ─────────────────────────────────────────────────────────────────────
help:
	@echo ""
	@echo "  $(PROJECT_NAME) — available commands (ENV=$(ENV))"
	@echo ""
	@echo "  Setup:"
	@echo "    make setup-server     One-time: create external network + volume"
	@echo "    make lock             Generate uv.lock"
	@echo "    make sync             Install deps locally via uv"
	@echo ""
	@echo "  Development:"
	@echo "    make dev              Start dev environment (build + up -d)"
	@echo "    make prod             Start prod environment (build + up -d)"
	@echo "    make stop             Stop all containers"
	@echo "    make restart          Restart all containers"
	@echo "    make logs             Follow logs from all services"
	@echo "    make ps               Show container status"
	@echo "    make shell            Bash inside the API container"
	@echo "    make db-shell         psql inside the DB container"
	@echo ""
	@echo "  Database:"
	@echo "    make migrate          Run Alembic upgrade head"
	@echo "    make migration m=...  Create new autogenerated migration"
	@echo "    make stamp-baseline   Mark current DB state as the baseline (one-time)"
	@echo ""
	@echo "  Testing:"
	@echo "    make test             Full suite (unit + integration, real test DB)"
	@echo "    make test-unit        Unit tests only (no DB needed)"
	@echo "    make test-from-dev    Seed test DB from dev dump, then run tests"
	@echo ""
	@echo "  Deployment:"
	@echo "    TEST_SERVER=user@host make deploy-test"
	@echo "    PROD_SERVER=user@host make deploy-prod"
	@echo ""
	@echo "  Quality:"
	@echo "    make lint             ruff check"
	@echo "    make format           ruff format"
	@echo ""

# ─── Dependency management (uv) ───────────────────────────────────────────────
lock:
	uv lock

sync:
	uv sync

# ─── Compose lifecycle ────────────────────────────────────────────────────────
dev:
	@$(MAKE) _up ENV=dev

prod:
	@$(MAKE) _up ENV=prod

_up:
	@echo "Starting $(ENV) environment..."
	$(COMPOSE) up --build -d
	@echo ""
	@echo "Status:"
	@$(COMPOSE) ps
	@echo ""
	@echo "URLs:"
	@echo "  Health:  http://localhost/health"
	@echo "  API:     http://localhost/api/docs"
	@echo "  Admin:   http://localhost/admin/"

stop:
	$(COMPOSE) down

restart:
	$(COMPOSE) restart

logs:
	$(COMPOSE) logs -f

ps:
	$(COMPOSE) ps

shell:
	docker exec -it $(PROJECT_NAME)-api /bin/bash

db-shell:
	docker exec -it $(PROJECT_NAME)-db sh -c \
	  'psql -U $$POSTGRES_USER -d $$POSTGRES_DB'

# ─── Database / migrations ────────────────────────────────────────────────────
migrate:
	docker exec $(PROJECT_NAME)-api alembic upgrade head

migration:
	@if [ -z "$(m)" ]; then echo "Usage: make migration m='your message'"; exit 1; fi
	docker exec $(PROJECT_NAME)-api alembic revision --autogenerate -m "$(m)"

stamp-baseline:
	docker exec $(PROJECT_NAME)-api alembic stamp 0001_baseline

# ─── Testing ──────────────────────────────────────────────────────────────────
TEST_COMPOSE = docker compose \
    --env-file env/.env.test.config \
    --env-file env/.env.test \
    -f docker/docker-compose.test.yml

# Pytest runs on the HOST, not in a container, so it needs the test env vars
# loaded into the shell before invocation. `set -a` exports every var defined
# by the sourced files. The test DB connection is rewritten in conftest.py
# from app-network host (myapp-test-db:5432) to host-network (localhost:5433).
PYTEST_ENV = set -a && . ./env/.env.test.config && . ./env/.env.test && set +a

test:
	@echo "Starting test database..."
	$(TEST_COMPOSE) up -d test-db
	@echo "Waiting for test DB to be healthy..."
	@for i in 1 2 3 4 5 6 7 8 9 10; do \
	    docker exec $(PROJECT_NAME)-test-db pg_isready -U $$(grep POSTGRES_USER env/.env.test.config | cut -d= -f2) >/dev/null 2>&1 && break; \
	    sleep 1; \
	done
	@echo "Loading test fixtures..."
	@docker exec -i $(PROJECT_NAME)-test-db sh -c \
	  'psql -U $$POSTGRES_USER -d $$POSTGRES_DB' < tests/fixtures/base_data.sql
	@echo "Running tests..."
	@bash -c '$(PYTEST_ENV) && uv run pytest tests/ -v --tb=short' || (status=$$?; $(TEST_COMPOSE) down; exit $$status)
	@echo "Tearing down test database..."
	$(TEST_COMPOSE) down

test-unit:
	@bash -c '$(PYTEST_ENV) && uv run pytest tests/unit/ -v --tb=short'

test-from-dev:
	@echo "Dumping dev database..."
	bash scripts/db_dump_dev.sh
	@echo "Restoring into test database..."
	$(TEST_COMPOSE) up -d test-db
	@for i in 1 2 3 4 5 6 7 8 9 10; do \
	    docker exec $(PROJECT_NAME)-test-db pg_isready >/dev/null 2>&1 && break; \
	    sleep 1; \
	done
	bash scripts/db_restore_test.sh
	@bash -c '$(PYTEST_ENV) && uv run pytest tests/ -v --tb=short -m "not requires_clean_data"'
	$(TEST_COMPOSE) down

# ─── Deployment ───────────────────────────────────────────────────────────────
deploy-test:
	bash scripts/deploy_test.sh

deploy-prod:
	@printf "About to deploy to PRODUCTION. Continue? [y/N] "; \
	read ans; \
	if [ "$$ans" = "y" ] || [ "$$ans" = "Y" ]; then \
	    bash scripts/deploy_prod.sh; \
	else \
	    echo "Aborted."; \
	fi

# ─── Setup ────────────────────────────────────────────────────────────────────
setup-server:
	bash scripts/create_network.sh

# ─── Code quality ─────────────────────────────────────────────────────────────
lint:
	uv run ruff check .

format:
	uv run ruff format .
