"""baseline — schema bootstrapped by docker/postgres/init/01_schema.sql

This migration intentionally does nothing. It exists so future autogenerated
migrations have a parent revision to chain from. The actual baseline schema
is created by Postgres on first container start (init script).

If you ever recreate the database without the init script (e.g. point Alembic
at a fresh DB), you'll need to either:
    1. Re-apply 01_schema.sql manually, then `alembic stamp 0001_baseline`
    2. Or rewrite this migration's upgrade() to create the baseline tables

Revision ID: 0001_baseline
Revises:
Create Date: 2026-04-16 00:00:00
"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
