#!/usr/bin/env bash
# init_project.sh — bootstrap a freshly-cloned boilerplate into a working project.
#
# Usage:
#   bash scripts/init_project.sh <project-name>
#
# What it does (in order):
#   1. Validates the project name
#   2. Renames "myapp" → <project-name> across the repo (calls rename_project.sh)
#   3. Generates env/.env.dev and env/.env.test with random POSTGRES_PASSWORD
#      and API_KEY values
#   4. Runs `uv lock` to produce uv.lock
#   5. Runs `make setup-server` (creates external Docker network + volume)
#   6. Replaces the boilerplate's .git directory with a fresh repo and makes
#      the first commit
#
# What it does NOT do:
#   - `make dev` (you should watch the Docker output the first time)
#   - `make stamp-baseline` (must run AFTER the DB container is up)
#   - Push to a remote (it doesn't know where you want it)

set -euo pipefail

# ─── Argument / name validation ───────────────────────────────────────────────
if [ $# -ne 1 ]; then
    echo "Usage: $0 <project-name>"
    echo "  Example: $0 customer-portal"
    exit 1
fi

NEW_NAME="$1"

if ! [[ "$NEW_NAME" =~ ^[a-z][a-z0-9_-]*$ ]]; then
    echo "Error: name must start with a lowercase letter and contain only [a-z0-9_-]"
    exit 1
fi

if [ ! -f "scripts/rename_project.sh" ]; then
    echo "Error: must be run from the project root (scripts/rename_project.sh not found)"
    exit 1
fi

# ─── Confirm ──────────────────────────────────────────────────────────────────
GIT_PRESENT="no"
[ -d ".git" ] && GIT_PRESENT="yes"

cat <<EOF

This will:
  1. Rename project:  myapp → ${NEW_NAME}
  2. Generate env/.env.dev   (random POSTGRES_PASSWORD, random API_KEY)
  3. Generate env/.env.test  (separate random secrets)
  4. Run \`uv lock\` to produce uv.lock
  5. Run \`make setup-server\` (docker network + volume named ${NEW_NAME})
  6. Replace .git with a fresh repo (current git history present: ${GIT_PRESENT})
     and create the initial commit "Initial setup for ${NEW_NAME}"

The boilerplate's git history will be DELETED.

EOF

read -r -p "Continue? [y/N] " ans
if [ "${ans:-N}" != "y" ] && [ "${ans:-N}" != "Y" ]; then
    echo "Aborted."
    exit 1
fi

# ─── 1+2. Rename ──────────────────────────────────────────────────────────────
echo
echo "==> Renaming myapp → ${NEW_NAME}..."
bash scripts/rename_project.sh "${NEW_NAME}"

# ─── 3. Generate dev/test env files ───────────────────────────────────────────
gen_env_file() {
    local target="$1"        # path to write
    local password="$2"      # postgres password
    local api_key="$3"       # api key
    local db_host="$4"       # e.g. ${NEW_NAME}-db or ${NEW_NAME}-test-db
    local db_name="$5"       # e.g. ${NEW_NAME} or ${NEW_NAME}_test

    if [ -f "$target" ]; then
        echo "  ${target} already exists — skipping (delete it and re-run if you want fresh secrets)"
        return
    fi

    cat > "$target" <<ENV
# Generated by init_project.sh on $(date +%Y-%m-%d) — gitignored, never commit.
POSTGRES_PASSWORD=${password}
DATABASE_URL=postgresql+asyncpg://${NEW_NAME}:${password}@${db_host}:5432/${db_name}
API_KEY=${api_key}

# External services — fill in when you start using them
ANTHROPIC_API_KEY=
POSTMARK_SERVER_TOKEN=
POSTMARK_FROM_EMAIL=
ENV
    echo "  Wrote ${target}"
}

echo
echo "==> Generating env files with random secrets..."
DEV_PW="$(openssl rand -hex 16)"
DEV_KEY="$(openssl rand -hex 32)"
TEST_PW="$(openssl rand -hex 16)"
TEST_KEY="$(openssl rand -hex 32)"

gen_env_file "env/.env.dev"  "$DEV_PW"  "$DEV_KEY"  "${NEW_NAME}-db"      "${NEW_NAME}"
gen_env_file "env/.env.test" "$TEST_PW" "$TEST_KEY" "${NEW_NAME}-test-db" "${NEW_NAME}_test"

# ─── 4. uv lock ───────────────────────────────────────────────────────────────
echo
echo "==> Running uv lock..."
uv lock

# ─── 5. setup-server ──────────────────────────────────────────────────────────
echo
echo "==> Running make setup-server..."
make setup-server

# ─── 6. Fresh git repo ────────────────────────────────────────────────────────
echo
echo "==> Replacing git history with a fresh repo..."
rm -rf .git
git init -b main >/dev/null
git add -A
git -c user.email="$(git config --global user.email || echo you@example.com)" \
    -c user.name="$(git config --global user.name || echo You)" \
    commit -m "Initial setup for ${NEW_NAME}

Bootstrapped from qz_boilerplate via scripts/init_project.sh.
" >/dev/null

# ─── Final instructions ───────────────────────────────────────────────────────
cat <<EOF

✅ ${NEW_NAME} is initialised.

Next steps:

  make dev                          # build images and start the stack
  make stamp-baseline               # one-time: mark Alembic at baseline
  curl http://localhost/health      # smoke-test FastAPI
  curl -H "x-api-key: \$(grep ^API_KEY env/.env.dev | cut -d= -f2)" \\
       http://localhost/api/v1/hello

When you're ready to push to a remote:

  gh repo create <org-or-user>/${NEW_NAME} --private --source=. --push

EOF
